### ISSUE TITLE
Bug: Malfunction issue in The Chromium Project.

### ISSUE THREAD

**Issue by Githubmaniak** [List-KR/NamuLink#102]
### URL

[namu.wiki](https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8)

### FILTERS

https://github.com/List-KR/NamuLink/issues/78

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

Tampermonkey

### USERSCRIPT

https://github.com/List-KR/NamuLink/issues/78

### Comment

![Screenshot_20240518-173828_Kiwi Browser](https://github.com/List-KR/NamuLink/assets/103377449/b9bf8637-0d83-44eb-a95a-c8dd84ebfe28)
We are experiencing an issue with content being removed from Chrome or The Chromium Project-based browser.  The tested browser is Kiwi Browser 124.0.6327.4 and ran on SM-G960N/Android 10.  The issue did not occur in Firefox, which is not a Blink-enabled browser.

**Comment by piquark6046** [comment]
Please reload the webpage.

**Comment by Githubmaniak** [comment]
@piquark6046 When I refresh the webpage, it displays normally, but when I move to another document, the content is removed and sometimes even when I refresh, the content is not displayed.  This time PowerLink started showing up again.
![Screenshot_20240519-003914_Kiwi Browser](https://github.com/List-KR/NamuLink/assets/103377449/f1c55aac-f090-4abf-8fe8-b463d926846a)

**Comment by piquark6046** [comment]
> This time PowerLink started showing up again.

Fixed by https://github.com/List-KR/NamuLink/pull/103.

**Comment by piquark6046** [comment]
Other issues are merged into 104.
