### ISSUE TITLE
Bug: namu.wiki

### ISSUE THREAD

**Issue by swbaek81** [List-KR/NamuLink#104]
### URL

https://namu.wiki/w/%EB%A1%9C%EB%A6%AC%EC%8A%A4%2520%EC%B9%B4%EB%A6%AC%EC%9A%B0%EC%8A%A4

### FILTERS

listkr 
마이크로쉴드
나무링크

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Userscript Manager

quoid/userscripts

### USERSCRIPT

마이크로쉴드
나무링크

### Comment

3.16.1 버전에서 글을 볼수 없습니다

![image](https://github.com/List-KR/NamuLink/assets/15683789/fa235a69-935c-45b2-85c1-0407c2802fb2)

**Comment by piquark6046** [comment]
임시 방편으로 아무 문서나 들어가신 뒤에 새로고침해보세요.

**Comment by swbaek81** [comment]
새로고침 해도 글을 볼수 없습니다

**Comment by KW1J** [comment]
저도 같은 증상입니다
namulink를 끄니 나무위키에 파워링크 광고가 뜨지만 문서는 읽을 수 있네요

**Comment by LMK93** [comment]
삼성 기본 브라우저 (삼성 인터넷) 쓰는데 같은 증상입니다.
이 증상은 새 탭 만들어서 나무위키 대문으로 들어갈때 문제가 생겼습니다.
이 증상은 비밀모드로 들어가려고 해도 문제가 생겼습니다.

새 탭을 만들고 주소창에서 'namu.wiki' 적어서 들어가면,
대문쪽으로 이동하기 때문에 문제가 생겼습니다.
이 증상이 생긴 탭에서 검색창으로 아무 문서로 들어가려 해도 저 모습이 그대로 나옵니다.
따라서 새로고침으로 증상이 개선되지 않았습니다. 

대신에 새 탭 띄울때 주소창에 입력하는 방식으로 
아무 문서로 들어가면 증상이 발현되지 않을 수도 있었습니다.
예 : 주소창에 'namu.wiki/w/애드가드'

하지만, Firefox를 사용하면 아래와 같은 문구가 나옵니다.
'이 웹서이트는 보안 연결이 필요합니다.'
고급으로 들어가면,
'https://namu.wiki 사이트는 HTTP Strict Transport Security (HSTS)라는 보안 정책을 가지고 있어서 Firefox가 보안 연결만 할 수 있습니다. 이 사이트를 방문하기 위해 예외를 추가 할 수 없습니다.'

이 상태에서는 무작위 문서로 들어가려고 해도 화면의 내용이 바뀌지 않았고,
새로고침해도 소용이 없었습니다.

**Comment by piquark6046** [comment]
유저스크립트가 브라우저나 앱의 TLS 레리어까지 접근할 수는 없습니다.

**Comment by piquark6046** [comment]
https://drive.google.com/file/d/1FaqfAmSGhI1NbiixhyHF75xpWTITVAlC/view?usp=sharing
저는 새로고침 몇 번 하니까 잘됩니다.
나무위키 메인 페이지 -> 아무 문서나 이동 -> 새로고침 진행

**Comment by swbaek81** [comment]
https://namu.wiki/w/%EB%A1%9C%EB%A6%AC%EC%8A%A4%2520%EC%B9%B4%EB%A6%AC%EC%9A%B0%EC%8A%A4

이 링크는 되나요? 아무리 해도 볼수 없네요

**Comment by LMK93** [comment]
> https://drive.google.com/file/d/1FaqfAmSGhI1NbiixhyHF75xpWTITVAlC/view?usp=sharing 저는 새로고침 몇 번 하니까 잘됩니다. 나무위키 메인 페이지 -> 아무 문서나 이동 -> 새로고침 진행

이게 문서마다 달랐습니다. 
새로고침이 먹히는 문서가 있고, 안먹히는 문서가 있었는데요.

참 이상한건,
유튜브링크가 있는 문서는 새로고침 해도 대체로 문제는 없었지만,
유튜브링크가 없는 문서는 새로고침 해도 증상이 생겼습니다.

**Comment by Githubmaniak** [comment]
https://namu.wiki/w/%EB%B9%84%ED%8A%B8%EC%86%8C%EB%8B%89/%EC%A0%9C%ED%92%88%20%EB%AA%A9%EB%A1%9D/%EC%82%AC%EC%9A%B4%EB%93%9C%20%EC%96%B4%EB%8C%91%ED%84%B0/%ED%86%A0%EC%9A%94%ED%83%80
일부 문서는 새로고침을 하면 잘 보입니다.
https://namu.wiki/w/%EB%8F%84%ED%82%A4%EC%B9%98%EB%A1%9C
다만 내용이 적은 문서는 내용이 사라지고 새로고침을 아무리해도 내용을 볼수 없습니다.
https://namu.wiki/w/%ED%94%84%EB%A1%9D%EC%8A%A4%ED%94%84%EB%A6%AC
신기한건 주석이 하나라도 달려있으면 내용이 적더라도 새로고침을 하면 표시가 됩니다.
Kiwi Browser를 사용하고있는데 Blink 엔진과 스크립트의 호환 오류인지 모르겠네요.

**Comment by piquark6046** [comment]
https://github.com/List-KR/NamuLink/issues/104#issuecomment-2119171344

Google Chrome와 Android 조합에서는 몇 번의 새로고침 후에 잘 로드됩니다.

--- 

https://github.com/List-KR/NamuLink/issues/104#issuecomment-2119251657

> https://namu.wiki/w/%EB%8F%84%ED%82%A4%EC%B9%98%EB%A1%9C
> https://namu.wiki/w/%ED%94%84%EB%A1%9D%EC%8A%A4%ED%94%84%EB%A6%AC

새로고침을 안해도 잘 보입니다.

**Comment by piquark6046** [comment]
그냥 ACL로 인해 편집 권한이 제한되게 설정된 문서에 한해 발생되는 듯합니다.

**Comment by swbaek81** [comment]
사파리에서는 3.16.2 버전에서도 안되네요
