### ISSUE TITLE
Bug: Entire contents in page are disappeared.

### ISSUE THREAD

**Issue by hankju84** [List-KR/NamuLink#108]
### URL

https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8

### FILTERS

AdGuard Base filter
AdGuard Mobile Ads filter
AdGuard Tracking Protection filter
AdGuard Social Media filter
AdGuard Annoyances filter
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Userscript Manager

quoid/userscripts

### USERSCRIPT

microShield, NamuLink

### Comment

![IMG_0616](https://github.com/List-KR/NamuLink/assets/73779442/27388801-f70d-4a5d-b816-eee9d99e1a0f)

**Comment by hankju84** [comment]
추가: 이것도 무작위로 발생하는 현상인 듯합니다.

**Comment by piquark6046** [comment]
문서 이름이 무엇인가요?

**Comment by hankju84** [comment]
나무위키:대문입니다.
꼭 대문이 아니어도 다른 페이지에서도 저 현상이 나타나더군요.

**Comment by piquark6046** [comment]
@hankju84 여전히 안됩니다.
https://drive.google.com/file/d/1BrZbObTKUSTtbiDgvjWEi5u5pwStaF0C/view?usp=sharing
