### ISSUE TITLE
Bug: some editor features are hidden

### ISSUE THREAD

**Issue by LDY0225** [List-KR/NamuLink#110]
### URL

https://namu.wiki/RecentChanges

### FILTERS

Namulink

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Android, uBlock Origin

### Userscript Manager

Tampermonkey

### USERSCRIPT

몇가지 버그가 나타나고 있습니다.

1)Namulink를 킨 상태에서는 로그인 창이 사라집니다.(상단 메뉴 바가 사라집니다.)

2)최근 변경(RecentChanges)가 로드되지 않고 최하단 메뉴만 나타납니다.

3)내 문서 기여목록(Documents)마찬가지로 로드되지 않고 최하단 메뉴만 나타납니다.

**Comment by piquark6046** [comment]
내 문서 기여목록을 보려면 계정이 필요하죠?

**Comment by LDY0225** [comment]
문서 기여목록 자체는 유동닉(IP계정)으로도 볼 수 있는 걸로 알고 있습니다.

**Comment by LDY0225** [comment]
현재(한국시간 기준 2024년 5월 29일 수요일 13시 24분)
2)최근 변경(RecentChanges)은 보입니다만

3)내 문서 기여목록(Documents)이 순간적으로 보였다 사라지는 현상이 여전히 나타나고 있습니다.

**Comment by piquark6046** [comment]
@LDY0225 3.16.5 버전으로 업데이트하신 후에 테스트해주세요.
3번째 이슈는 제 환경에서는 재구현이 어렵네요.
