### ISSUE TITLE
AD: 최하단 파워링크 광고차단이 되지 않습니다.

### ISSUE THREAD

**Issue by jadeclub3** [List-KR/NamuLink#112]
### URL

- https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8

- https://namu.wiki/w/%EB%8B%B9%EB%8B%B9%EC%B9%98%ED%82%A8

- https://namu.wiki/w/%EA%B0%9C%EB%B3%B5%EC%B9%98

- https://namu.wiki/w/%EA%B6%8C%EC%9C%A8

.
.
.

모든 나무위키 문서

### FILTERS

Ublock₀ 제공
5/5

uBlock filters
5/5
50,504개 중 49,849개 사용 중
광고
3/3

EasyList
87,269개 중 86,547개 사용 중

AdGuard – Ads
81,071개 중 75,011개 사용 중

AdGuard – Mobile Ads
9,410개 중 9,259개 사용 중
개인정보
2/4

EasyPrivacy
50,998개 중 50,086개 사용 중

Block Outsider Intrusion into LAN
66개 중 66개 사용 중
멀웨어 도메인
2/2

Online Malicious URL Blocklist
13,355개 중 13,355개 사용 중

Phishing URL Blocklist
518개 중 518개 사용 중
다목적
1/2

Peter Lowe’s Ad and tracking server list
3,726개 중 3,726개 사용 중
쿠키 알림
4/4

EasyList/uBO – Cookie Notices
2/2
52,251개 중 47,107개 사용 중

AdGuard/uBO – Cookie Notices
2/2
30,987개 중 30,916개 사용 중
소셜 위젯
3/3

EasyList – Social Widgets
16,232개 중 16,194개 사용 중

AdGuard – Social Widgets
23,146개 중 21,495개 사용 중

Fanboy – Anti-Facebook
68개 중 68개 사용 중
골칫거리
9/9

EasyList – Annoyances
4/4
15,377개 중 15,244개 사용 중

AdGuard – Annoyances
4/4
49,268개 중 46,812개 사용 중

uBlock filters – Annoyances
5,913개 중 5,881개 사용 중
지역, 언어
1/36

kr kr: List-KR
4,968개 중 4,923개 사용 중

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Userscript Manager

Violentmonkey

### USERSCRIPT

- NamuLink

- microShield

### Comment

![화면 캡처 2024-05-31 121135](https://github.com/List-KR/NamuLink/assets/43388905/f8ad9bba-aaf3-4009-8f6d-0f3b7a0c4a4b)

한 달 전쯤 부터 스크립트가 쭉 작동을 안 하는 것 같습니다. 모든 나무위키 문서 최하단의 파워링크가 그대로 노출됩니다. (간헐적인 게 아니고 계속 노출됨)
깃허브 이슈란 계속 체크하고 업데이트도 수동으로 생각날 때마다 했는데 고쳐질 기미가 안 보여서 직접 이슈 작성합니다. 
혹시 더 필요한 제 환경의 정보가 필요하시면 알려주세요. 감사합니다

**Comment by piquark6046** [comment]
NamuLink 버전은 무엇인가요?

**Comment by jadeclub3** [comment]
> NamuLink 버전은 무엇인가요?

3.16.5
라고 표시됩니다

**Comment by piquark6046** [comment]
재구현이 안됩니다.
나무위키 내에서 sankawa 스킨을 사용하도록 설정하셨나요?

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/List-KR/NamuLink/assets/98787049/6f9e2510-e41c-4050-9c87-c5260a0f7021)


</p>
</details>

**Comment by jadeclub3** [comment]
> 재구현이 안됩니다. 나무위키 내에서 sankawa 스킨을 사용하도록 설정하셨나요?
> 
> Screenshot
> ![image](https://private-user-images.githubusercontent.com/98787049/335442395-6f9e2510-e41c-4050-9c87-c5260a0f7021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjk0NzMsIm5iZiI6MTcxNzEyOTE3MywicGF0aCI6Ii85ODc4NzA0OS8zMzU0NDIzOTUtNmY5ZTI1MTAtZTQxYy00MDUwLTljODctYzUyNjBhMGY3MDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA0MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiODU2ZmRjODAyZTFmMjA1ZGQyZGJiMTEzNWJiMDcxOTY5MjhmOGM0ZTI4MjM0NmZmZjM2MDM3NGQ2MTBkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgeS6efo5kiQGFB1oWUXC0aiJwyFppWYqpB0v4RmXrk)

아니요 기본 스킨 사용중입니다

![화면 캡처 2024-05-31 132151](https://github.com/List-KR/NamuLink/assets/43388905/a248141b-5920-4c2f-bfcd-de4f304789d6)

그런데 님이 올린 스샷 보고
시크릿모드로 스크립트 없이 열어보니 파워링크가 원래는 각주 바로 위에 표시되는데
저 같은 경우에는 각주 최하단(웹페이지 최하단)에 표시가 되네요

이게 증상이랑 관련이 있을까요?

**Comment by jadeclub3** [comment]
선생님 제가 지금 무슨 조건인지 알아냈는데 확인 부탁드려요

설정 > 위키 > 분류 위치
에서 상단을 선택하면 문제가 없는데
하단을 선택하면 파워링크가 노출되네요

![화면 캡처 2024-05-31 132908](https://github.com/List-KR/NamuLink/assets/43388905/b5d0912c-d6a2-4e0a-b635-178eb4bcb0de)

**Comment by piquark6046** [comment]
그러면 나무위키 페이지가 로드된 상태에서 다른 페이지로 넘어갔을 때는 괜찮나요?

**Comment by jadeclub3** [comment]
> 그러면 나무위키 페이지가 로드된 상태에서 다른 페이지로 넘어갔을 때는 괜찮나요?

그건 지금 해봤는데 파워링크 표시랑은 관계없는 것 같네요

그런데 바로 위에 답글 혹시 보셨나요? https://github.com/List-KR/NamuLink/issues/112#issuecomment-2141215072
확인 부탁드립니다
