### ISSUE TITLE
AD: namulink

### ISSUE THREAD

**Issue by bobblun** [List-KR/NamuLink#123]
### URL

https://namu.wiki/w/%EB%A7%90%EB%9D%BC%EC%9C%84

### FILTERS

namulink

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

AdGuard for Android

### USERSCRIPT

나무링크 유저스크립트만 활성화해도 광고 차단이 되지 않습니다

![Screenshot_20240611_164757_Samsung Internet](https://github.com/List-KR/NamuLink/assets/49634687/34ca2336-1a02-4d0d-b789-eb8b493a8b7e)
![Screenshot_20240611_164819_AdGuard](https://github.com/List-KR/NamuLink/assets/49634687/41c31d04-083f-46b8-90b3-17f165038831)

**Comment by piquark6046** [comment]
방금 4.0.2 버전이 올라갔으니 업데이트해보세요.

**Comment by bobblun** [comment]
> 방금 4.0.2 버전이 배포되었으니 업데이트해보세요. #122

이슈 해결되었으므로 닫습니다
