### ISSUE TITLE
Image does not load

### ISSUE THREAD

**Issue by RoonMoonlight** [List-KR/NamuLink#13]
### URL

https://namu.wiki/w/WDG

### FILTERS

* uBlock filters
* uBlock filters – Badware risks
* uBlock filters – Privacy
* uBlock filters – Quick fixes
* uBlock filters – Resource abuse
* uBlock filters – Unbreak
* EasyList
* EasyPrivacy
* Online Malicious URL Blocklist
* Fanboy’s Annoyance
* Fanboy’s Social
* Peter Lowe’s Ad and tracking server list
* List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Userscript Manager

Violentmonkey

### USERSCRIPT

* NamuLink
* microShield

### Comment

![image](https://user-images.githubusercontent.com/25527589/220116095-9332e9f6-4879-4087-a5af-d79161fda8e7.png)
The image disappears when NamuLink is active. Seems wiki admin made an update to the NamuLink detection script.

**Comment by piquark6046** [comment]
Confirmed. I will investigate your issue.

**Comment by piquark6046** [comment]
Resolved.
@RoonMoonlight Check on your side.
