### ISSUE TITLE
AD: Keep showing ads in FireFox

### ISSUE THREAD

**Issue by MigKei** [List-KR/NamuLink#179]
### URL

https://namu.wiki/w/%EC%B6%A9%EB%8F%99%EA%B5%AC%EB%A7%A4%EC%9E%A5%EC%95%A0#s-8

### FILTERS

uBlock filters
5/5

광고
1/3
EasyList

개인정보
1/4
EasyPrivacy

멀웨어 도메인
1/2
Online Malicious URL Blocklist

다목적
1/2
Peter Lowe’s Ad and tracking server list

지역, 언어
2/36
[jp]  jp: AdGuard Japanese

[kr]  kr: List-KR

사용자 지정
2/2
AakList (Anti-Adblock Killer)

YousList

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Userscript Manager

Tampermonkey

### USERSCRIPT

None except namulink

### Comment

며칠 전에 템퍼몽키에서 나무링크 업데이트 한 이후로 맨 아랫줄 광고가 계속 표시됩니다.
안 보고 싶은데 방법이 있을까요? 유블럭 오리진 쓰고 있고 템퍼몽키로는 나무링크만 씁니다.

![캡처](https://github.com/user-attachments/assets/2c3a7afd-986d-4a6e-84bc-e8f77927dc9e)

**Comment by piquark6046** [comment]
5.0.2 으로 테스트해주세요

**Comment by piquark6046** [comment]
NamuLink 6.0.0 버전으로 업데이트 해주세요

**Comment by MigKei** [comment]
해보니까 pc 파폭에서 정상적으로 되네요. 감사합니다.
