### ISSUE TITLE
AD: Namuwiki powerlink

### ISSUE THREAD

**Issue by hoochukim** [List-KR/NamuLink#182]
### URL

https://namu.wiki/w/%EA%B0%95%EB%85%B8%EC%9D%84

### FILTERS

![image](https://github.com/user-attachments/assets/79f90f54-3334-4b11-b3da-5f54893c9997)
![image](https://github.com/user-attachments/assets/9a5f39b1-18e3-4527-add9-4cb8d5edf12b)
![image](https://github.com/user-attachments/assets/266d5bf4-62ff-4b48-81b7-cd67616ac056)

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Userscript Manager

AdGuard for Windows

### USERSCRIPT

![image](https://github.com/user-attachments/assets/1c0a6a5a-58b4-41a4-9e4d-f1aee8f41abb)
![image](https://github.com/user-attachments/assets/77b7e048-c01e-4fa6-b1d8-c27ce91db01b)

네이버 검색을 통해 나무위키 접속이나, 나무위키 내 실시간 검색어 탭을 통해 문서 이동시에 나무위키 하단에 파워링크가 지속적으로 노출이 됩니다.
나무링크 버전 5.1.7 입니다.
어제 다른 게시글 보고 노출되는거 해결되는거 같다가 다시 노출되네요.
하단부 파워링크 노출되는 것은 정상인건가요?

**Comment by piquark6046** [comment]
5.1.8 버전으로 업데이트해보세요

**Comment by hoochukim** [comment]
> 5.1.8 버전으로 업데이트해보세요

5.1.11 버전인데 나무위키 문서 하단 탭에 지속적으로 노출되고있습니다.

**Comment by piquark6046** [comment]
@hoochukim 5.2.0 버전에서도 동일하나요?

**Comment by hoochukim** [comment]
> @hoochukim 5.2.0 버전에서도 동일하나요?

 아뇨 하단부 탭에 광고가 노출되지 않습니다.
