### ISSUE TITLE
Bug: app initialization failed

### ISSUE THREAD

**Issue by gwg02153** [List-KR/NamuLink#184]
### URL

https://namu.wiki/

### FILTERS

Aaklist
Nocoin filter list
ADshield disable
Adguard 베이스 필터
Easylist

### Browser

Mozilla Firefox, Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Userscript Manager

AdGuard for Windows

### USERSCRIPT

Namulink'
Tynyshield

### Comment

![캡처](https://github.com/user-attachments/assets/cdf555c7-a135-4df8-81fd-e25aed60d86d)
5.2.0 버전 스크립트 설치 후 크롬에서 나무위키를 접속하면 저렇게 되네요. 메인 화면은 일정확률로 멀쩡하지만 검색해서 다른 문서에 들어가면 저렇게 됩니다.
파이어폭스도 비슷한데 에러창이 훨씬 더 길고요

**Comment by ilkils00** [comment]
삼성인터넷에서도 동일한 에러가 나타납니다.
