### ISSUE TITLE
Bug: Captcha not shown when using VPN

### ISSUE THREAD

**Issue by Starush-1** [List-KR/NamuLink#19]
### URL

https://namu.wiki/

### FILTERS

NamuLink

### Browser

Mozilla Firefox

### Operating System

Apple macOS

### Ad-Blocker

uBlock Origin

### Userscript Manager

Tampermonkey

### USERSCRIPT

NamuLink

### Comment

VPN 으로 접속 시 Cloudflare의 Captcha 페이지가 뜨는데, NamuLink 스크립트 사용 시 페이지에서 Captcha 항목이 나타나지 않아서 나무위키를 열람할 수가 없습니다.

**Comment by piquark6046** [comment]
어느 VPN을 사용하셨나요?

**Comment by piquark6046** [comment]
재구헌 가능합니다.
