### ISSUE TITLE
AB: 나무위키 파워링크가 계속 표시되는데 이걸 어떻게 해결할수는 없나요?

### ISSUE THREAD

**Issue by Githubmaniak** [List-KR/NamuLink#2]
### URL

https://namu.wiki/w/나무위키:대문

### FILTERS

AdGuard Base filter, Mobile Ad Filter, Social Filter, Annoyances, DNS Filter, Search ads and self promotion, List-KR, YouList

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro, (Other)

### Userscript Manager

(Other)

### USERSCRIPT

namulink.user.js

### Comment

나무위키의 파워링크에 링크가 눌러지지 않는것 까진 좋은데 이걸 완전히 제거할수는 없나요?

**Comment by piquark6046** [comment]
@Githubmaniak Can you share a screenshot?

**Comment by Githubmaniak** [comment]
@piquark6046 
![3778DBD8-1301-47BB-B860-D7A04FE4A798](https://user-images.githubusercontent.com/103377449/185088456-d30e477d-15ab-48c8-974a-8e3971095eeb.png)

**Comment by piquark6046** [comment]
Hmm... Is it your first visit in the opened tab [^1]? Or, did you reload NamuWiki?

[^1]: It means that did you visit NamuWiki via an external webpage?

**Comment by Githubmaniak** [comment]
@piquark6046 There are times when accessing through other links, but most of them are accessed by entering the URL in the tab.

**Comment by Githubmaniak** [comment]
@piquark6046 I never reloaded it.

**Comment by piquark6046** [comment]
@Githubmaniak Can you access macOS?

**Comment by Githubmaniak** [comment]
@piquark6046 I don't have a mac.

**Comment by piquark6046** [comment]
@Githubmaniak
Have you kept log-in status during browsing NamuWiki?

**Comment by Githubmaniak** [comment]
@piquark6046 Yes.  I've logged in once and never logged out.

**Comment by Githubmaniak** [comment]
@piquark6046 I updated but still the powerlink is showing.
![AC69EA92-0B06-489A-B8D2-88C1CCB92999](https://user-images.githubusercontent.com/103377449/185171892-d5b5db1a-50ac-4ea6-87df-3278cefa3637.png)

**Comment by piquark6046** [comment]
Did you reload the website?

**Comment by Githubmaniak** [comment]
@piquark6046 Yes.  When I run Safari now, the power link disappears whether the process has been initialized in memory.
![2332A85E-30D3-4F34-B33A-BF0E5790B9A4](https://user-images.githubusercontent.com/103377449/185183109-b08c8cc2-0b06-432c-b0a4-9dbe5630dcfe.png)

**Comment by piquark6046** [comment]
@Githubmaniak Please test NamuLink 1.2.6.

**Comment by Githubmaniak** [comment]
@piquark6046 When I add namu.wiki###adcr.naver.com to AdGuard's user rules and activate the corresponding user script, it works, but Naver Power Link is displayed on Wi-Fi other than at home.

**Comment by Githubmaniak** [comment]
@piquark6046 The updated version also works fine.
