### ISSUE TITLE
AD: namu.wiki

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/NamuLink#24]
### URL

https://namu.wiki/w/AFC%20%EC%95%84%EC%8B%9C%EC%95%88%EC%BB%B5

### FILTERS

AdGuard 베이스 필터
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Userscript Manager

(Other)

### USERSCRIPT

NamuLink

### Comment

![IMG_2830](https://github.com/List-KR/NamuLink/assets/126370491/2558da1d-0308-4b18-9db9-92071e7c5e24)
셀룰러 데이터(통신사 IP)로 들어가면 광고가 없는데, 와이파이로 들어가면 파워링크가 노출됩니다. 아이폰뿐만 아니라 안드로이드폰에서도 마찬가지입니다.

와이파이 자체가 원인이라기보단 IP에 따라 노출 여부가 결정되는 것 같아요. 아이폰의 비공개 릴레이를 사용하여 IP가 임의로 변경되면 와이파이를 켠 상태에서도 파워링크가 노출되지 않습니다.

**Comment by piquark6046** [comment]
유저스크립트를 설치하시는데 어떤 앱을 사용하셨나요?

**Comment by piquark6046** [comment]
UI가 업데이트되었네요.

**Comment by relaxedbrownie** [comment]
아이폰은 https://apps.apple.com/kr/app/userscripts/id1463298887
안드로이드폰은 AdGuard 자체 기능요.

**Comment by piquark6046** [comment]
처음부터 다시 작성하는게 나을 수도 있겠네요.

**Comment by piquark6046** [comment]
수정했습니다. 업데이트해주세요.

**Comment by Melon394** [comment]
> 수정했습니다. 업데이트해주세요.

목차 아래에 공백이 남는데 없앨 수 없을까요?

**Comment by piquark6046** [comment]
스크린샷 보내주세요.

**Comment by piquark6046** [comment]
@Melon394 스크린샷 보내주세요.

**Comment by Melon394** [comment]
> @Melon394 스크린샷 보내주세요.

![0001](https://github.com/List-KR/NamuLink/assets/156186083/4ae0e361-e1fe-4128-adc8-0ee076b51a14)

**Comment by piquark6046** [comment]
https://github.com/List-KR/NamuLink/issues/24#issuecomment-1913076593
파워링크 광고가 아니라서 List-KR 필터에서 처리됩니다.

**Comment by piquark6046** [comment]
고쳤습니다.

**Comment by Melon394** [comment]
> 고쳤습니다.

업데이트했는데 공백이 아직 나옵니다. 기기 해상도에 따라 보여지는 광고에 조금 차이가 있는 듯합니다

pc 및 태블릿- 상단의 문서 항목명 아래¹에 파워링크 아닌 일반 광고, ¹에 광고 있었던 공백 남아있음, 목차 아래²에는 원래 광고 없음,
폰 - ¹자리에 파워링크, (0.5초쯤 파워링크 보였다가 사라짐, 공백x), ²에 일반광고 있었던 공백 남아있음

분류:, 틀:로 분류되는 문서들에서는 기기해상도 무관하게 ¹에 일반 광고가 뜨고 공백이 남아있는 것 같습니다

**Comment by piquark6046** [comment]
@Melon394 새 issue로 열어주세요.
