### ISSUE TITLE
AD: Leaking ads after NamuWiki update

### ISSUE THREAD

**Issue by potav** [List-KR/NamuLink#26]
### URL

Every document including https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4

### FILTERS

Built in uBlock filters
AdGuard - Mobile Ads
Block Outsider Intrusion into LAN
EasyPrivacy
Online Malicious Blocklist
Peter Lowe's Ad and tracking server list
List-KR
Actually Legitimate URL Shortener Tool
Privacy Essentials
yokoffing's Annoyance List
EasyList (Optimized)
Fanboy's Annoyances (Optimized)
HaGeZi's Personal DNS Blocklist
HaGeZi's The World's Most Abused TLDs
Privacy Extended

### Browser

Mozilla Firefox

### Operating System

Android

### Ad-Blocker

uBlock Origin

### Userscript Manager

Violentmonkey

### USERSCRIPT

NamuLink

### Comment

NamuWiki's website layout is recently updated. Ads are leaking and there is a new PowerLink ad  under the title.

**Comment by piquark6046** [comment]
Please provide a screenshot and your ISP.

**Comment by piquark6046** [comment]
@potav

**Comment by potav** [comment]
![Screenshot_20240127-202325_Firefox Nightly](https://github.com/List-KR/NamuLink/assets/116474873/cb8ad68f-9538-40a2-ae42-81f60a0abb90)
![Screenshot_20240127-202337_Firefox Nightly](https://github.com/List-KR/NamuLink/assets/116474873/16f8ce0a-186f-45fe-ae7b-0ffdd81106df)
ISP is SKT.

**Comment by piquark6046** [comment]
Please show console tab of the DevTool via Firefox's `about:debugger` in Firefox Desktop.

**Comment by piquark6046** [comment]
@potav

**Comment by potav** [comment]
Recently my laptop broke so I can't test it myself. Sorry.

**Comment by piquark6046** [comment]
@potav then, please reinstall uBlock Origin.

**Comment by potav** [comment]
It worked. Thank you very much.
