### ISSUE TITLE
Bug: 이런 식으로 중간광고가 나옵니다

### ISSUE THREAD

**Issue by LDY0225** [List-KR/NamuLink#40]
### URL

https://namu.wiki/w/%EC%95%84%EC%82%B0%EC%9D%B4%EC%88%9C%EC%8B%A0%EC%B2%B4%EC%9C%A1%EA%B4%80
https://namu.wiki/w/%EC%82%AC%EC%A7%81%EC%8B%A4%EB%82%B4%EC%B2%B4%EC%9C%A1%EA%B4%80
https://namu.wiki/w/%EB%B6%80%EC%B2%9C%EC%8B%A4%EB%82%B4%EC%B2%B4%EC%9C%A1%EA%B4%80

### FILTERS

###w0kH1SOzv > div.\33 deabe8a:nth-child(2) > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.ah5Pf-Tl > article.MO5qdfWb:first-child > div:nth-child(5) > div > div > div > div > div > div:nth-child(4) > div > div.def63bda:nth-child(8) > div:first-child > div.EpTH711b > div.L8gWKhM3:nth-child(2) > br 

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Userscript Manager

Tampermonkey

### USERSCRIPT

###w0kH1SOzv > div.\33 deabe8a:nth-child(2) > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.\33 deabe8a > div.ah5Pf-Tl > article.MO5qdfWb:first-child > div:nth-child(5) > div > div > div > div > div > div:nth-child(4) > div > div.def63bda:nth-child(8) > div:first-child > div.EpTH711b > div.L8gWKhM3:nth-child(2) > br 

### Comment

![adreport_01](https://github.com/List-KR/NamuLink/assets/162461468/a5976436-f65d-46c7-806e-1c7074fb1f65)

이런식으로 '둘러보기 틀'과 '본문' 사이에 광고로 여겨지는 것이 나옵니다.

그렇다고 해서 Adguard로 '비슷한 규칙 적용'을 하면 이런 식으로
![adreport_false](https://github.com/List-KR/NamuLink/assets/162461468/e619fa31-032b-44d6-a5ed-1947dbe22607)
모든 내용이 사라지는 버그가 나타납니다.

버그 내지는 Namuwiki 측에서 방해를 하고 있는 거 같은데 해결 가능하시다면 조치 부탁드립니다. 

감사합니다.

추신

한국어를 아신다면
https://gall.dcinside.com/mgallery/board/view/?id=namuwiki&no=82046&page=8  이 글에서 이야기하는 내용과 본 내용이 일치합니다.

Userscript에 단 내용은 모든 내용이 안 보이는 것을 막아보기 위해 adguard값을 최소까지 낮춘 결과 나온 내용입니다.
![adreport_01](https://github.com/List-KR/NamuLink/assets/162461468/dd7dddf8-94d9-4978-a98a-fa10db7b1a83)

**Comment by piquark6046** [comment]
광고가 있던 자리가 아니고 해당 나무위키 문서에 `[clearfix]` 가 사용되어 빈 공간이 존재하는 것 같습니다.
편집기로 한번 확인해보세요.
