### ISSUE TITLE
Bug: 잘못된 이미지 차단

### ISSUE THREAD

**Issue by AcousticAmbitiousCats** [List-KR/NamuLink#43]
### URL

https://namu.wiki/w/%EC%97%84%ED%81%AC

### FILTERS

LIST KR

### Browser

Mozilla Firefox, Google Chrome, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Userscript Manager

AdGuard for Windows, AdGuard for Android

### USERSCRIPT

microShield
Namulink

### Comment

나무링크를 활성화하면 문서 최상단에 있는 이미지가 안 보임

**Comment by piquark6046** [comment]
스크린샷을 보내주세요.

**Comment by AcousticAmbitiousCats** [comment]
![스크린샷 2024-03-12 020952](https://github.com/List-KR/NamuLink/assets/163019535/148dac4a-4dc9-4a55-954f-443a1744b3e2)
![스크린샷 2024-03-12 020941](https://github.com/List-KR/NamuLink/assets/163019535/6f53b910-bb33-4426-a298-4ac4ab26638b)

**Comment by piquark6046** [comment]
고쳤습니다. 업데이트해주세요.
