### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by sssh7710** [List-KR/NamuLink#5]
### URL

https://namu.wiki/w/%EA%B0%A4%EB%9F%AD%EC%8B%9C%20A33%205G

### FILTERS

YousList 
list-kr

### Browser

Google Chrome

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

AdGuard for Android

### USERSCRIPT

![Screenshot_20220831-100528_Chrome](https://user-images.githubusercontent.com/98168192/187571634-fa8a05e1-3917-4f69-9a5e-9520c3e095f9.jpg)

### Comment

The page cannot be loaded. Only Google Chrome has this problem. Samsung browsers do not show this phenomenon.

**Comment by sssh7710** [comment]
The editing page cannot be loaded.

**Comment by piquark6046** [comment]
@sssh7710 
Editing page of a NamuWiki article can be loaded on my side.
Also, your main issue [^1] cannot be reproduced on [Bromite](https://github.com/bromite/bromite) based on Chromium.

[^1]: https://namu.wiki/w/%EA%B0%A4%EB%9F%AD%EC%8B%9C%20A33%205G is not loaded.

Can you reset data of Google Chrome?

**Comment by sssh7710** [comment]
> @sssh7710 나무위키 기사의 편집 페이지는 내 쪽에서 불러올 수 있습니다. 또한 Chromium 기반 [Bromite](https://github.com/bromite/bromite) 에서는 주요 문제 [1](#user-content-fn-1-5a4323c21491805ce777822c055b888e) 을 재현할 수 없습니다 .[](https://github.com/bromite/bromite)
> 
> Chrome의 데이터를 재설정할 수 있습니까?
> 
> ## 각주
> 1. https://namu.wiki/w/%EA%B0%A4%EB%9F%AD%EC%8B%9C%20A33%205G 가 로드되지 않았습니다.[↩](#user-content-fnref-1-5a4323c21491805ce777822c055b888e)

The connection is good right now
