### ISSUE TITLE
Bug: namu.wiki

### ISSUE THREAD

**Issue by bobblun** [List-KR/NamuLink#51]
### URL

namu.wiki

### FILTERS

list-kr
namulink

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

AdGuard for Android

### USERSCRIPT

https://github.com/List-KR/NamuLink/issues/49

삼성 브라우저 쿠키 쪽에 문제가 생겼나봅니다 쿠키를 삭제하면 나무링크가 정상적으로 작동하여 파워링크가 차단되지만,
이후 위 링크의 스크린샷처럼 광고는 차단되지만 파워링크 틀 자체는 사라지지 않습니다

다시 쿠키를 삭제하면 없어지지만 이후 다시 광고 파워링크 틀이 되살아납니다

**Comment by piquark6046** [comment]
삭제하신 후에 언제 다시 증상이 나타나나요?

**Comment by piquark6046** [comment]
메일은 filters@adguard.com 나 piquark6046@proton.me 으로 보내주세요.

**Comment by bobblun** [comment]
> 메일은 [filters@adguard.com](mailto:filters@adguard.com) 나 [piquark6046@proton.me](mailto:piquark6046@proton.me) 으로 보내주세요.

첫번째 메일로 보냈습니다

**Comment by piquark6046** [comment]
확인했습니다. 나무위키 비로그인 상태에서 글씨 크기를 크게하고 리로드하면 발생하네요.

**Comment by bobblun** [comment]
> 확인했습니다. 나무위키 비로그인 상태에서 글씨 크기를 크게하고 리로드하면 발생하네요.

로그인해도 발생합니다 글씨 크기 쪽에 문제나 있나봅니다

**Comment by piquark6046** [comment]
고쳤습니다.
