### ISSUE TITLE
AdGuard 팝업 차단기 유저스크립트를 사용할 때 나무위키 로드 오류

### ISSUE THREAD

**Issue by razrholic** [List-KR/NamuLink#68]
### 문제 해결 방법으로 즉시 이동: https://github.com/List-KR/NamuLink/issues/68#issuecomment-2085265452

---

### URL

https://namu.wiki/w/AdGuard

### FILTERS

AdGaurd 베이스 필터
AdGaurd URL 추적 필터
AdGaurd 추적 보호 필터
AdGaurd 소셜미디어 필터
List-KR
YousList

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Userscript Manager

AdGuard for Windows

### USERSCRIPT

Adguard Extra (Beta)
Adguard 팝업차단기 (Beta)
microShield
NamuLink(3.6.0)

### Comment

![image](https://github.com/List-KR/NamuLink/assets/168492289/16b949a9-3b21-42d6-8401-e0d58b694c67)
![image](https://github.com/List-KR/NamuLink/assets/168492289/de3b63a6-2275-4d6a-b095-25892a09c70a)
Enabling NamuLink 3.6.0 results in infinite load

**Comment by piquark6046** [comment]
아래 규칙를 사용자 규칙에 추가해주세요.
```adblock
@@||namu.wiki^$extension="AdGuard Popup Blocker"
```

**Comment by razrholic** [comment]
> 아래 규칙를 사용자 규칙에 추가해주세요.
> 
> ```
> @@||namu.wiki^$extension="AdGuard Popup Blocker"
> ```

It worked. thank you.
