### ISSUE TITLE
AD: Power link ad display issue at the bottom of namu wiki

### ISSUE THREAD

**Issue by Githubmaniak** [List-KR/NamuLink#78]
### URL

https://namu.wiki/w/EMV%20Contactless

### FILTERS

- AdGuard Base Fillter
- AdGuard Mobile Fillter
- AdGuard Social Fillter
- AdGuard Annoyances Fillter
- Adblock Warning Removal List
- Online Malicious URL Blocklist
- Pishing URL Blocklist
- Youslist
- List-KR
- Filter unblocking search ads and self-promotion
- AdGuard DNS Filter
- Fanboy's Anti-thirdparty Fonts

### Browser

Mozilla Firefox, (Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

Tampermonkey

### USERSCRIPT

- Namulink
- microShield
- Return Youtube Dislike
- AdGuard Extra

### Comment

![Screenshot_20240503-180818_Kiwi Browser](https://github.com/List-KR/NamuLink/assets/103377449/5510320b-d8e9-4147-9b86-c6def5422d4f)
![Screenshot_20240503-181257_Firefox Nightly](https://github.com/List-KR/NamuLink/assets/103377449/7228a6ea-eb3e-4498-a939-0854a89da060)
(Top) Kiwi Browser, (Bottom) Firefox Nightly

Even if you use Namulink, the Power Link advertisement at the bottom is not removed, and there is a problem where the Power Link advertisement at the top is sometimes displayed.

I thought it was a problem with Kiwi Browser, so I installed namulink in Firefox Nightly, but it was the same.

**Comment by Kinomerc** [comment]
**URL**
https://namu.wiki/w/(Every Docu)

**FILTERS**
Using filter on this page without filter of ublock -> https://github.com/yokoffing/filterlists

**Operating System**
Android, Windows

**Ad-Blocker**
AdGuard for Android
Adguard for windows

**Userscript Manager**
adguard app and program(premium feature)

**USERSCRIPT**
- using on android and windows both
Namulink
microShield
跟踪链接净化
네이버 검색 주소 단축
linkproduct-privacy
Twitter Prime
AMP 비활성화
Selection and Copying Restorer (Universal)
Twitter hide content warning crap
MoreCAPTCHA
Show and reload broken images
Namu Hot Now
Arca base64 autodecoder
oo.pe redirection remover

- using only on pc
YouTube CPU Tamer by AnimationFrame
Unhold YouTube Resource Locks
YouTube Anti-Shorts Script (modified)
YouTube Always show progress bar
Return YouTube Dislike
유튜브 댓글 번역 버튼
YouTube Super Fast Chat
Youtube - Fix channel links in sidebar recommendations
YouTube Repeated Recommendations Hider
Cleanup YouTube Recommendations in Search and Playlist
치지직-팔로우방송알림
CHZZK Live Progress Slider
MegaCloud Auto Password Decrypter

**Comment**
suffer sameproblem in pc and mobile
maybe, powerlink mechanism(?) of namuwiki was changed
![제목 없음](https://github.com/List-KR/NamuLink/assets/96902592/02b65f94-bd4a-4b9e-ad4d-f0560c54df50)
![1](https://github.com/List-KR/NamuLink/assets/96902592/88fec626-d8a1-43c9-9a22-7662e4e4c35e)
![2](https://github.com/List-KR/NamuLink/assets/96902592/5f823b80-f3f8-4f0c-8921-5abfec5ddb06)

**Comment by piquark6046** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18568
