### ISSUE TITLE
파워링크가 페이지 이동시 차단이 안됩니다

### ISSUE THREAD

**Issue by tjtnsgns** [List-KR/NamuLink#8]
처음 들어갈 시에는 정상적으로 차단이 되는 데 차단된 페이지에서 다른 페이지로 이동시 파워링크가 나타납니다. 새로고침을 하면 정상적으로 사라지기 합니다만 
![1000000016](https://user-images.githubusercontent.com/28147257/203261108-7bd8107a-a6dd-4562-a191-4b31aa34c5a7.jpg)

**Comment by tjtnsgns** [comment]
예시 동영상입니다

**Comment by piquark6046** [comment]
duplicate of #7
