### ISSUE TITLE
AD: PowerLink is finally blocked, but there is a slight problem.

### ISSUE THREAD

**Issue by Githubmaniak** [List-KR/NamuLink#80]
### URL

https://namu.wiki/w/%EB%B9%84%ED%8A%B8%EC%86%8C%EB%8B%89/%EC%A0%9C%ED%92%88%20%EB%AA%A9%EB%A1%9D/%EC%82%AC%EC%9A%B4%EB%93%9C%20%EC%96%B4%EB%8C%91%ED%84%B0/%ED%86%A0%EC%9A%94%ED%83%80

### FILTERS

https://github.com/List-KR/NamuLink/issues/78

Same as the list of the corresponding thread.

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

Tampermonkey

### USERSCRIPT

https://github.com/List-KR/NamuLink/issues/78

Same as the list of the corresponding thread.

### Comment

![Screenshot_20240504-013741_Kiwi Browser](https://github.com/List-KR/NamuLink/assets/103377449/a581d420-5d6f-49ac-9442-2f889756e9d2)
![Screenshot_20240504-013748_Kiwi Browser](https://github.com/List-KR/NamuLink/assets/103377449/c9e78365-4e0a-4502-9b95-d578c2f2ac70)

When you first access Namuwiki, a blank space appears in the power link area at the top and the power link at the bottom is displayed as is, but when you refresh, both are removed.  It was tested on Kiwi Browser and SM-G955N, and is presumed to be the same for other browsers.

**Comment by piquark6046** [comment]
@Githubmaniak 
Please update to 3.11.0 and try again.
