### ISSUE TITLE
Bug: Request failed with status code 404 오류가 계속해서 나타납니다.

### ISSUE THREAD

**Issue by LDY0225** [List-KR/NamuLink#90]
### URL

Namuwiki

### FILTERS

list-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Android, uBlock Origin

### Userscript Manager

Tampermonkey

### USERSCRIPT

Namulink

### Comment

Reloading Page
통신 오류가 발생하여 새로고침을 시도합니다.
Request failed with status code 404

대략 이런 식의 오류가 계속 발생하며 새로고침을 무한반복하다가 원래 하려 했던 문서이동,편집,문서저장 등을 막습니다. 대략 이 오류가 발생한 것은 한국시간으로 5월 14일 12~13시 즈음이였고, 22시 즈음에는 편집조차 막는 등 그 오류의 형태가 발전했습니다.

일단 Namuwiki가 본 Namulink를 막기 위해 훼방을 놓는 것은 분명해 보입니다. 왜냐하면 대략 이 오류가 발생한 것은 한국시간으로 5월 14일 12~13시 즈음이였고, 22시 즈음에는 편집조차 막는 등 그 오류의 형태가 발전했습니다.

https://board.namu.wiki/b/qna/2945671?p=1
이 글에서 보다시피 Yor라는 관리자가 노골적으로 'NamuLink를 끄세요.'라고 단답형으로 일방적으로 문의를 종료한 것을 보아하니(아실 분은 아시겠지만 이 Yor라는 관리자는 대단히 불량스러운 관리자이며, 유저를 겁박하는 것을 취미로 삼는 자입니다.)

Namuwiki 측에서 Namulink이용을 방해하기 위해 어떤 수작을 부리는 것이 분명해 보입니다.

Namuwiki가 무시로 일관하기로 한 이상 이 Bug가 고쳐지기를 바랍니다.

![error_01](https://github.com/List-KR/NamuLink/assets/162461468/eb991c5c-2c72-4eef-bd8a-b18a68f35226)
![error_02](https://github.com/List-KR/NamuLink/assets/162461468/54112207-c31d-427a-b17a-2b78effaacda)

**Comment by piquark6046** [comment]
문제가 발생하면 새로운 issue를 open해주세요.
