### ISSUE TITLE
powerlink reappears.

### ISSUE THREAD

**Issue by Moore2512** [List-KR/NamuLink#91]
### URL

https://namu.wiki

### FILTERS

adguard base
adguard mobile
youslist
list kr
adguard dns

### Browser

Google Chrome, Naver Whale, Samsung Internet

### Operating System

Microsoft Windows 10, Android

### Ad-Blocker

AdGuard Browser Extension, AdGuard for Android

### Userscript Manager

Violentmonkey

### USERSCRIPT

Namulink

### Comment

The powerlink at the bottom of the document reappears.

**Comment by piquark6046** [comment]
문제가 발생하면 새로운 issue를 open해주세요.
