### ISSUE TITLE
AD: 3.14.0 PC버전 파워링크 차단

### ISSUE THREAD

**Issue by bobblun** [List-KR/NamuLink#94]
### URL

namu.wik

### FILTERS

list-kr
베이스필터
namulink

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Android

### Userscript Manager

AdGuard for Windows

### USERSCRIPT

![3 14](https://github.com/List-KR/NamuLink/assets/49634687/a31c2ad9-6235-41ff-bb0d-44530de2c318)

나무링크 3.14 버전 

구글 크롬 PC로 사용시 맨 밑 나무링크는 차단이 되지 않음 맨위는 차단OK
(모바일 버전은 차단 정상작동 확인)

**Comment by piquark6046** [comment]
3.15.0 으로 업데이트해주세요.
