### ISSUE TITLE
Bug: accecpted editrequest access is dinied

### ISSUE THREAD

**Issue by LHM138Z** [List-KR/NamuLink#96]
### URL

https://namu.wiki/RecentDiscuss?logtype=accepted_editrequest

### FILTERS

 * Adguard 베이스 필터
 * Adguard 모바일 필터
 * Adguard 일본어 필터
 * YousList
 * List-KR

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Userscript Manager

AdGuard for Android

### USERSCRIPT

 * Anti-Adblock Kiler(Reek)
 * Namulink
 * microShield

### Comment

When namulink is activated, access to the accepted edit request page is blocked.

![Screenshot_20240515_185719_Samsung Internet](https://github.com/List-KR/NamuLink/assets/48651498/8b30dd7c-5711-4ce2-b418-68a6aa477367)

**Comment by piquark6046** [comment]
3.14.1 기준으로 잘 표시됩니다.

**Comment by piquark6046** [comment]
@LHM138Z  3.15.0 으로 업데이트해주세요.
