### ISSUE TITLE
Bug: 문서 안 보임

### ISSUE THREAD

**Issue by AcousticAmbitiousCats** [List-KR/NamuLink#97]
### URL

https://namu.wiki/w/110.12
https://namu.wiki/w/%EB%B6%84%EB%A5%98:%EC%A0%9C%EB%AA%A9%EC%9D%B4%20%EC%88%AB%EC%9E%90%EC%9D%B8%20%EB%AC%B8%EC%84%9C

### FILTERS

list kr

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Userscript Manager

AdGuard for Windows

### USERSCRIPT

namu link
microshield

### Comment

110.12 문서는 제목 안 보임
2번째 링크는 내용 통째로 날아감

**Comment by piquark6046** [comment]
잘 보입니다.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/List-KR/NamuLink/assets/98787049/3cee5999-c039-45c2-98fe-ff5db9d1969a)


</p>
</details>

**Comment by piquark6046** [comment]
@AcousticAmbitiousCats 3.15.0 으로 업데이트해주세요.

**Comment by AcousticAmbitiousCats** [comment]
해결됐습니다 감사합니다
